# Generated by Django 2.2.5 on 2020-08-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_news', '0002_auto_20200811_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
